openapi: 3.0.0
info: 
  title: Songs API
  version: 0.0.1

paths:
  /:      #paths object
    get:  #path item object
      summary: Returns a greeting message from Songs API  #operation object
      operationId: getGreeting                            #operation object
      responses:                                              #operation object
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Hello from Songs API"

  /songs:
    get:
      summary: Returns all songs
      operationId: getSongs
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AllSongs'
    post:
      summary: Create a new song
      operationId: createSong
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSongRequest'

      responses:
        '201':
          description: Song created successfully.
          headers:
            Location:
              description: URL of the created song.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateSongResponse'
        '400':
          description: Bad request. Invalid field(s) in request body.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '409':
          description: Conflict with already existing song.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SongAlreadyExists'






components:
  schemas:
    AllSongs:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: The id of the song.
        name:
          type: string
          description: The name of the song.
        artist:
          type: string
          description: Artist who recorded the song.
        publish_year:
          type: integer
          format: int32
          description: The year the song was recorded.
      example:
        - id: 0fa4ab70-379c-423e-8a89-c1fd344c685c
          name: Thunderstruck
          artist: AC/DC
          publish_year: 1990
        - id: 2fd527f0-d068-4834-ad64-5ddc60fcbba8
          name: Rokkibaby
          artist: Frederik
          publish_year: 1975
    CreateSongRequest:
      required:
        - name
        - artist
        - publish_year
      properties:
        name:
          type: string
          description: The name of the song.
        artist:
          type: string
          description: Artist who recorded the song.
        publish_year:
          type: integer
          format: int32
          description: The year the song was recorded.
      example:
        - name: The Thrill is Gone
          artist: B.B. King
          publish_year: 1969
    CreateSongResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: The id of the song.
        name:
          type: string
          description: The name of the song.
        artist:
          type: string
          description: Artist who recorded the song.
        publish_year:
          type: integer
          format: int32
          description: The year the song was recorded.
      example:
        - id: 7ccc951a-25cf-4009-bfb1-b8ef4300db46
          name: The Thrill is Gone
          artist: B.B. King
          publish_year: 1969

    SongAlreadyExists:
      type: object
      properties:
        message:
          type: string
          example:  "Song with provided name(name of the song), artist(artist of the song) and publish_year(publish_year of the song) already exists."
    BadRequest:
      type: object
      properties:
        message:
          type: string
        errors:
          type: object
          additionalProperties:
            type: string
            description: Validation error message for the specific field
          example:
            artist: "must not be blank"
            name: "must not be blank"
            publish_year: "publish_year must be between 1889 and the current year."
      required:
        - message
        - errors
